language: python
python:
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install redisco with dependencies
install:
  - pip install . --use-mirrors
# command to run tests
script: nosetests --with-doctest
services:
  - redis-server
